services:
  - type: web
    name: icfoldsignal
    runtime: python

    buildCommand: pip install -r requirements.txt
    startCommand: python app.py

    healthCheckPath: /health

    envVars:
      - key: SYMBOL
        value: BTCUSDT

      - key: INTERVAL
        value: 1m

      - key: POLL_SECONDS
        value: "5"

      - key: TELEGRAM_TOKEN
        sync: false

      - key: TELEGRAM_CHAT_ID
        sync: false
