services:
  - type: web
    name: icfoldsignal
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    healthCheckPath: /health

    envVars:
      - key: SYMBOL
        value: BTCUSDT

      - key: POLL_SECONDS
        value: "1"

      - key: CooldownMinutes
        value: "3"

      - key: RSI_Period
        value: "8"

      - key: RSI_OverBuy
        value: "70"

      - key: RSI_OverSell
        value: "30"

      - key: Sto_OverBuy_Crs
        value: "70"

      - key: Sto_OverSell_Crs
        value: "30"

      - key: Sto_OverBuy_Ext
        value: "80"

      - key: Sto_OverSell_Ext
        value: "20"

      - key: BB_Period
        value: "20"

      - key: BB_Dev
        value: "2"

      - key: MA1_Period
        value: "10"

      - key: MA2_Period
        value: "21"

      - key: MA3_Period
        value: "30"

      - key: MA4_Period
        value: "50"

      - key: TELEGRAM_TOKEN
        sync: false

      - key: TELEGRAM_CHAT_ID
        sync: false۱۱۱۱۱۱۱۱۱۱۱۱۱۱۱۱۱۱۱۱۱۱۱۱۱۱۱۱۱۱۱۱۱۱۱۱۱۱۱۱۱۱۱۱۱۱۱
